"""Last-edited dates, and an automatic "new" badge, from the git history.

Two things come out of one pass over `git log`:

1. Every page gets a "last update" line at the bottom, rendered by Material's
   own template. The hook sets `page.meta["git_revision_date_localized"]`, which
   is the key Material already looks for, so no template override is needed.
2. Pages touched in the last `WINDOW_DAYS` days are listed in a generated
   JavaScript file. `docs/assets/javascripts/whats-new.js` reads that list and
   badges the page title and its entry in the sidebar.

A page created inside the window is "new"; one merely edited inside it is
"updated". The "pending" badge on unfinished sections is separate, and that script
works it out from the gap markers in the page itself.

No plugin and no extra dependency. It needs the repository's real history, so
`fetch-depth: 0` is set in the deploy workflow. With a shallow clone or no git at
all, every date comes back empty, nothing is badged, and the build still works.
"""

import json
import logging
import os
import subprocess
import urllib.parse
from datetime import datetime, timedelta, timezone

log = logging.getLogger("mkdocs.hooks.last_edited")

WINDOW_DAYS = 30
MARKER = "@@commit@@"
DATA_FILE = "assets/javascripts/whats-new-data.js"

# Keyed by the page's path relative to docs_dir, e.g. "life/wellness.md".
_dates: dict[str, dict[str, datetime]] = {}


def _fmt(moment: datetime) -> str:
    """"9 September 2026". Avoids %-d, which Windows does not support."""
    return f"{moment.day} {moment:%B %Y}"


def _run(args: list[str], cwd: str) -> str:
    return subprocess.run(
        args, cwd=cwd, capture_output=True, text=True, timeout=60, check=True,
    ).stdout


def _git_dates(docs_dir: str) -> dict[str, dict[str, datetime]]:
    """Walk the whole history once, newest commit first.

    For each file the first date seen is its last edit, and the last date seen is
    when it first appeared. `git log` reports paths from the repository root, so
    they are re-keyed against docs_dir to match MkDocs.
    """
    try:
        root = _run(["git", "rev-parse", "--show-toplevel"], docs_dir).strip()
        out = _run(
            ["git", "log", "--no-merges", f"--pretty=format:{MARKER}%cI",
             "--name-only"],
            root,
        )
    except (subprocess.SubprocessError, OSError) as err:
        log.warning("last_edited: no usable git history (%s)", err)
        return {}

    prefix = os.path.relpath(docs_dir, root).replace(os.sep, "/")
    prefix = "" if prefix == "." else prefix + "/"

    dates: dict[str, dict[str, datetime]] = {}
    commit = None
    for line in out.splitlines():
        if line.startswith(MARKER):
            commit = datetime.fromisoformat(line[len(MARKER):])
            continue
        if not line or commit is None:
            continue
        if prefix and not line.startswith(prefix):
            continue
        key = line[len(prefix):]
        entry = dates.setdefault(key, {"updated": commit, "created": commit})
        entry["created"] = commit          # overwritten until the oldest commit wins
    return dates


def on_config(config, **kwargs):
    global _dates
    _dates = _git_dates(str(config.docs_dir))
    if not _dates:
        log.info("last_edited: no dates found; pages will carry no timestamp")
    return config


def on_files(files, config, **kwargs):
    """Generate the data file that the front-end script reads."""
    cutoff = datetime.now(timezone.utc) - timedelta(days=WINDOW_DAYS)
    recent: dict[str, dict] = {}

    for file in files.documentation_pages():
        url = "" if file.url in ("./", ".") else file.url
        entry: dict[str, object] = {}

        dates = _dates.get(file.src_uri)
        if dates and dates["updated"] >= cutoff:
            entry["state"] = "new" if dates["created"] >= cutoff else "updated"
            entry["date"] = _fmt(dates["updated"])

        if entry:
            recent[url] = entry

    # The script compares against location.pathname, so it needs the path the
    # site is served under. "" is the home page.
    base = urllib.parse.urlparse(config.site_url or "/").path or "/"
    payload = json.dumps({"base": base, "windowDays": WINDOW_DAYS,
                          "pages": recent}, indent=2, sort_keys=True)
    content = ("/* Generated by hooks/last_edited.py. Do not edit. */\n"
               f"window.CPH_WHATS_NEW = {payload};\n")

    try:
        from mkdocs.structure.files import File
        files.append(File.generated(config, DATA_FILE, content=content))
    except (ImportError, AttributeError):        # MkDocs too old to generate files
        log.warning("last_edited: this MkDocs cannot generate files, so the "
                    "'new' badges are skipped")
    return files


def on_page_markdown(markdown, page, config, files, **kwargs):
    """Hand Material the date it already knows how to render."""
    dates = _dates.get(page.file.src_uri)
    if dates:
        page.meta["git_revision_date_localized"] = _fmt(dates["updated"])
    return markdown
